### ISSUE TITLE
Terminer la conception de l'upload de photos

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/GL51-excercice1#2]
En tant qu’utilisateur de l’application de stockage de photos
Lorsque je remonte une photo dans l’application
Alors La photo est redimensionnée en 1024*1024 px
Et un thumbnail de taille 50*50 px est généré, avec le logo de mon appli en filigrane
Et les deux images sont stockées sous mon cloud
Et la base de données est mise à jour avec les coordonnées et le nom du fichier

Terminer la conception du problème ci dessus.
remonter le résultat sous github et poster ici un lien vers ce résulat, avec votre nom/prénom

**Comment by martin-plessy** [comment]
Martin Plessy : https://gist.github.com/martin-utbm/aa10364e0c74c70287ef1adfe226004e

**Comment by dbissari** [comment]
Déromba Serge Bissari : https://gist.github.com/dbissari/8ac7420c4ea418c842e3ec8ffe4f816c

**Comment by Integrale18** [comment]
https://gist.github.com/Integrale18/a7e78ac9146b9788cdb694314b0d66a1

**Comment by BorisBrogle** [comment]
Boris Brogle : https://gist.github.com/BorisBrogle/5946b613aab24577cd3539f91b205908

**Comment by YannPoncet** [comment]
Yann Poncet: https://gist.github.com/YannPoncet/ce70620236aa9aa94fefd647e81590cb

**Comment by RodolphePonthon** [comment]
Rodolphe Ponthon : https://gist.github.com/RodolphePonthon/67e16712968b9864248e36c99910e8c7

**Comment by albanPezzoli** [comment]
Alban Pezzoli : https://gist.github.com/albanPezzoli/ae34beb23786eab217b78be23519fcba

**Comment by Tibdub** [comment]
Thibault Dubois : https://gist.github.com/Tibdub/0b4e27b60a2b257a7402b58fdf0e4554

**Comment by linda-jemni** [comment]
Linda Jemni : https://gist.github.com/linda-jemni/d1363538d18418888e70e3764d0336d8

**Comment by linda-jemni** [comment]
Linda Jemni: https://gist.github.com/linda-jemni/88d6e78f893d697dd3c02e71090fcb69

**Comment by EloiseGrillet** [comment]
Éloïse Grillet : https://gist.github.com/EloiseGrillet/98f917456d2adc04f2adb8442cfa373a

**Comment by ThomasGubien** [comment]
Thomas Gubien : https://gist.github.com/ThomasGubien/d54f2a5a930779c3e3074093b2f2f8d9

**Comment by blomios** [comment]
Bouteiller Anthony : https://gist.github.com/blomios/cdb42ea8d0dacefa80c6bd1e9313173a

**Comment by ghost** [comment]
Heydel Luc : https://gist.github.com/lheydel/24d2e775cf1d938badc83fa159787ff5

**Comment by tanzhang666** [comment]
Tan Zhang:https://gist.github.com/solarzttt/70b51bbbe3c8818977fc675aae8e6d2e

**Comment by Czq96** [comment]
Zhuoqi CHEN : https://gist.github.com/Czq96/3e49018cc87bfaeb69b7a700331e71b3

**Comment by Wying96** [comment]
Ying WU ：https://gist.github.com/Wying96/2b8acbd18113ddc3260f9d3c9af4ce85

**Comment by Albtadini** [comment]
AL BTADINI Faraj: https://github.com/Albtadini/GL51/blob/master/Exercice%202

**Comment by shuxuzhipeng** [comment]
https://github.com/shuxuzhipeng/gl51/blob/master/gl51td1.txt

**Comment by wdjousse** [comment]
William djousse : https://gist.github.com/wdjousse/17a6951d4a84a266bf3267e7dbb131ad

**Comment by aitianshi** [comment]
Etienne Filhol : https://gist.github.com/aitianshi/bd40902ed6f44d4854186127bc183969

**Comment by balmajoe** [comment]
https://gist.github.com/balmajoe/649fc8fc629f18f860a6ae1e5451b756

**Comment by arona504** [comment]
Arona GUEYE : https://gist.github.com/arona504/5a671c6effb47e9fd71238eaf2c81e28

**Comment by science162** [comment]
Mouaffo Régis : https://gist.github.com/science162/26a12334c08bba48e4bdfb5c722b9579

**Comment by CCHENJiajie** [comment]
Jiajie CHEN : https://github.com/CCHENJiajie/GL51/blob/master/exercise2

**Comment by ccripSong** [comment]
sicong HUANG : https://gist.github.com/ccripSong/bb76c73614922498777e58c05fa586d1

**Comment by XinyuSHAN** [comment]
xinyu SHAN : https://gist.github.com/XinyuSHAN/e4f2f999ad7cf88e64cc902053e4e631

**Comment by vokt** [comment]
Vanessa Kameni : https://gist.github.com/vokt/cfd5e8e6a1efdd04e81f0c093c453048

**Comment by zikas96** [comment]
https://github.com/zikas96/test/blob/master/tp1.java

**Comment by LPA2-Automne2016** [comment]
Je viens de corriger, j'ia vu des devoirs avec des choses très claires dans les esprits, d'autres devoirs sont par contre carrément très obscurs !

Je corrige cela la prochaine fois pour tout remettre au clair
